In [2]:
import numpy as np

## Creating arrays

In [4]:
a= np.array([1,2,3,4,5])   # create an array
a

array([1, 2, 3, 4, 5])

In [5]:
a.ndim # checking the dimension

1

In [6]:
a=np.array([[1,2,3,4,5],[4,7,5,2,1]]) #creating 2 dimensional array
a

array([[1, 2, 3, 4, 5],
       [4, 7, 5, 2, 1]])

In [7]:
a.ndim

2

In [8]:
# create a 3 dimensional array

a=np.array([[[1,2,3,4,5],[4,7,5,2,1],[1,2,3,4,5]]])
a

array([[[1, 2, 3, 4, 5],
        [4, 7, 5, 2, 1],
        [1, 2, 3, 4, 5]]])

In [9]:
a.ndim

3

## Zero's and One's

In [10]:
var=np.zeros(10)

In [11]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
var1=np.ones(10)

In [14]:
var1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [16]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

## Functions

In [17]:
var=np.array([22,56,33,45])
var

array([22, 56, 33, 45])

In [18]:
type(var)

numpy.ndarray

In [19]:
var.argmax() # max value in index position.

1

In [20]:
var.argmin()

0

In [21]:
var[3]

45

In [22]:
var[0]

22

In [23]:
var[1]

56

In [24]:
var

array([22, 56, 33, 45])

In [25]:
var[0:2]

array([22, 56])

In [26]:
var[1:3]

array([56, 33])

In [27]:
var[0:-1]

array([22, 56, 33])

In [32]:
arr4=np.array([1,2,5,4.0,5,6,7,8,9])
arr4

array([1., 2., 5., 4., 5., 6., 7., 8., 9.])

In [30]:
arr4.dtype

dtype('float64')

In [31]:
arr4.size

9

In [ ]:
# Create a numpy array with size 5 and dataype of float

In [33]:
arr5=np.array([1,2,3,4,5.1])
arr5

array([1. , 2. , 3. , 4. , 5.1])

In [34]:
arr5.size

5

In [35]:
# create a two dim array
# four arrays in the external array
# it should have two elements each

In [37]:
#Tanmay
ar=np.array([[1,2],[3,4],[5,6],[7,8]])
ar


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [38]:
ar.ndim

2

## Resize & Reshape

In [51]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
a.ndim

1

In [42]:
w=np.arange(12).reshape(4,3)
w

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
w.ndim

2

In [49]:
q=a.reshape(6,2)
q

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
a.reshape(5,2)

ValueError: cannot reshape array of size 12 into shape (5,2)

In [50]:
q.shape

(6, 2)

In [52]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
a.max()

11

In [54]:
a.min()

0

In [56]:
x=np.array([4,16,25,81])

In [57]:
np.sqrt(x)

array([2., 4., 5., 9.])

In [58]:
np.log(x)

array([1.38629436, 2.77258872, 3.21887582, 4.39444915])

In [59]:
np.exp(x)

array([5.45981500e+01, 8.88611052e+06, 7.20048993e+10, 1.50609731e+35])

## Transpose

In [60]:
q=a.reshape(6,2)
q

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [61]:
t=q.T
t

array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

## floor & Ceil

In [67]:
arr2=np.array([10.8,3.65,1.8,97.21,1.2])
arr2

array([10.8 ,  3.65,  1.8 , 97.21,  1.2 ])

In [68]:
np.floor(arr2)

array([10.,  3.,  1., 97.,  1.])

In [69]:
np.ceil(arr2)   # it is giving the next integer value

array([11.,  4.,  2., 98.,  2.])

In [70]:
round_data=np.round(arr2)

In [71]:
round_data

array([11.,  4.,  2., 97.,  1.])

## stacking

In [72]:
arr2=np.arange(10).reshape(2,5)
arr3=np.arange(20).reshape(4,5)

In [73]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [76]:
np.vstack((arr2,arr3))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [77]:
np.hstack((arr2,arr3))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 4

In [80]:
arr2=np.arange(10).reshape(5,2)
arr3=np.arange(20).reshape(5,4)

In [81]:
arr2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [82]:
arr3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [79]:
np.hstack((arr2,arr3))

array([[ 0,  1,  0,  1,  2,  3],
       [ 2,  3,  4,  5,  6,  7],
       [ 4,  5,  8,  9, 10, 11],
       [ 6,  7, 12, 13, 14, 15],
       [ 8,  9, 16, 17, 18, 19]])

- ## For vertical stack the number of column should be equal, for horizondal stacking the number of rows should be equal.

## Numpy slit

In [83]:
arr28= np.arange(100).reshape(10,10)
arr28

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [84]:
np.vsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])]

In [85]:
np.hsplit(arr28,2)

[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [ ]:
? # Create a numpy array with the shape of 20,10 and divide it into 2 equal parts horizondally.

In [86]:
arr24 = np.arange(200).reshape(20,10)
arr24
np.hsplit(arr28,2)


[array([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54],
        [60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84],
        [90, 91, 92, 93, 94]]),
 array([[ 5,  6,  7,  8,  9],
        [15, 16, 17, 18, 19],
        [25, 26, 27, 28, 29],
        [35, 36, 37, 38, 39],
        [45, 46, 47, 48, 49],
        [55, 56, 57, 58, 59],
        [65, 66, 67, 68, 69],
        [75, 76, 77, 78, 79],
        [85, 86, 87, 88, 89],
        [95, 96, 97, 98, 99]])]

In [87]:
arr24

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
       [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
       [160, 161, 162, 163, 164, 165, 166, 167, 168, 169