In [1]:
# l1 regularization techniques- Lasso Regression
# l2 regularization techniques- Ridge Regression

In [2]:
import numpy as np
import pandas as pd

In [3]:
df=pd.read_csv('50_Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.shape

(108, 5)

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [6]:
df.State=le.fit_transform(df.State)

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [8]:
X= df.drop(columns=['Profit'],axis=1)
X.head()

R&D Spend  Administration  Marketing Spend  State
0  165349.20       136897.80        471784.10      2
1  162597.70       151377.59        443898.53      0
2  153441.51       101145.55        407934.54      1
3  144372.41       118671.85        383199.62      2
4  142107.34        91391.77        366168.42      1

In [9]:
y = df.Profit
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [10]:
from sklearn.preprocessing import MinMaxScaler
scalar=MinMaxScaler()

In [11]:
X_scaled=pd.DataFrame(scalar.fit_transform(X),columns=X.columns)
X_scaled.head()

R&D Spend  Administration  Marketing Spend  State
0   1.000000        0.651744         1.000000    1.0
1   0.983359        0.761972         0.940893    0.0
2   0.927985        0.379579         0.864664    0.5
3   0.873136        0.512998         0.812235    1.0
4   0.859438        0.305328         0.776136    0.5

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_scaled,y,test_size=0.2,random_state=1)

In [14]:
x_train.shape

(86, 4)

In [15]:
x_test.shape

(22, 4)

In [16]:
from sklearn.linear_model import Ridge

In [17]:
r=Ridge()

In [18]:
r.fit(x_train,y_train)

Ridge()

In [36]:
ridge_pred=r.predict(x_test)
ridge_pred

array([128938.5046324 , 176979.29309609, 165342.13784147, 182972.32194291,
       126495.39965377, 116689.2702612 ,  57970.81942831, 140651.85531533,
        58099.6447174 , 121351.73214744, 108694.87050998, 170663.71552393,
        58099.6447174 , 124215.89399843, 130375.69502591, 141698.9074917 ,
       127903.16738832,  77853.49432376, 114306.13126963, 116689.2702612 ,
       130375.69502591, 147254.65803551])

In [38]:
ridge_pred_train = r.predict(x_train)
ridge_pred_train

array([117682.74335894,  55342.94443976, 101869.05903689,  97099.08821588,
        75190.98967051,  70076.08924777,  99192.16516652,  75285.97857641,
       142252.66473248,  80742.68222677, 129895.69029966,  95130.94295339,
        97946.77437244, 108694.87050998, 121351.73214744,  85477.58150927,
        84052.66086523,  88133.24730107, 108805.58197231,  72033.52283072,
        88133.24730107,  82414.32538157,  75190.98967051,  82030.50437688,
        77853.49432376, 114306.13126963,  95171.54038964, 152288.96988651,
       156747.70496601, 161502.86535409, 142252.66473248, 140651.85531533,
       170663.71552393,  82665.04387383, 126495.39965377,  58771.41897261,
       129895.69029966, 124215.89399843, 108805.58197231, 130375.69502591,
        69272.86919386, 102587.0618291 , 111406.05118602,  99719.37198043,
        80742.68222677,  57970.81942831, 121930.10529159, 165342.13784147,
        98331.75498903,  55342.94443976,  70076.08924777, 147254.65803551,
       121930.10529159, 1

In [21]:
from sklearn.linear_model import Lasso

In [22]:
l=Lasso()

In [23]:
l.fit(x_train,y_train)

Lasso()

In [39]:
lasso_pred=l.predict(x_test)
lasso_pred

array([134252.95556388, 182130.39065807, 171722.80117119, 188584.59464343,
       128502.5841758 , 115745.63087393,  51952.77044278, 146111.44859109,
        57969.50513374, 115876.25386019, 116998.26275856, 178719.675717  ,
        57969.50513374, 125236.88382486, 130282.97590516, 153869.57408432,
       128711.89542969,  73412.82930324, 111124.61002218, 115745.63087393,
       130282.97590516, 150312.12571022])

In [40]:
lasso_pred_train = l.predict(x_train)
lasso_pred_train

array([115660.5445472 ,  49837.09831451, 100085.24760725,  95193.34850358,
        60318.592823  ,  66138.77726346,  99987.71547136,  69070.44460651,
       146680.7135205 ,  76337.54851402, 135071.30938151,  99191.64210192,
        91432.14408213, 116998.26275856, 115876.25386019,  78106.94099846,
        80562.29981063,  86078.13706713, 110830.00264868,  69307.44724153,
        86078.13706713,  76563.04578035,  60318.592823  ,  75705.52737644,
        73412.82930324, 111124.61002218,  88542.25990828, 156709.81797926,
       162894.74989675, 169745.2994421 , 146680.7135205 , 146111.44859109,
       178719.675717  ,  79117.3577237 , 128502.5841758 ,  54178.31339961,
       135071.30938151, 125236.88382486, 110830.00264868, 130282.97590516,
        65737.16320928, 101224.40461692, 116313.39708847, 102844.30991751,
        76337.54851402,  51952.77044278, 117884.83947543, 171722.80117119,
       101399.36783058,  49837.09831451,  66138.77726346, 150312.12571022,
       117884.83947543, 1

In [26]:
y_test

100    144259.40
90     191792.06
92     182901.99
89     192261.83
101    141585.52
55     126992.93
88      14681.40
54     129917.04
48      35673.41
66     105008.31
58     122776.86
2      191050.39
87      35673.41
102    134307.35
56     125370.37
95     156122.51
107    124266.90
42      71498.49
62     108733.99
105    126992.93
17     125370.37
97     152211.77
Name: Profit, dtype: float64

In [27]:
profit=pd.DataFrame({'Actual_y_value':y_test,'Ridge_pred':ridge_pred,'Lasso_pred':lasso_pred})
profit.head(10)

Actual_y_value     Ridge_pred     Lasso_pred
100       144259.40  128938.504632  134252.955564
90        191792.06  176979.293096  182130.390658
92        182901.99  165342.137841  171722.801171
89        192261.83  182972.321943  188584.594643
101       141585.52  126495.399654  128502.584176
55        126992.93  116689.270261  115745.630874
88         14681.40   57970.819428   51952.770443
54        129917.04  140651.855315  146111.448591
48         35673.41   58099.644717   57969.505134
66        105008.31  121351.732147  115876.253860

# Evaluation Metrics for Regression

In [ ]:
## MSE- Mean square error

## RMSE- Root Mean square error

## R2-score

In [28]:
from sklearn import metrics

In [33]:
## mse

print(metrics.mean_squared_error(y_test,ridge_pred))
print(metrics.mean_squared_error(y_test,lasso_pred))

256098039.44822857
176077236.36707115


In [34]:
# RMSE

print(np.sqrt(metrics.mean_squared_error(y_test,ridge_pred)))
print(np.sqrt(metrics.mean_squared_error(y_test,lasso_pred)))

16003.063439486472
13269.409797239332


In [35]:
## R2-score

print(metrics.r2_score(y_test,ridge_pred))
print(metrics.r2_score(y_test,lasso_pred))

0.8891579480292655
0.9237918328999641


In [41]:
# R2 score on Training data

print(metrics.r2_score(y_train,ridge_pred_train))
print(metrics.r2_score(y_train,lasso_pred_train))

0.9135616159568721
0.9342846515438199


In [42]:
# training  accu:lasso- 0.9342846515438199
# test accur:lasso- 0.9237918328999641